SS:
	gcc simpleserver.c -o ss
	gcc simpleclient.c -o sc
TH:
	gcc thread_server.c -o TS -lpthread 
	gcc thread_client.c -o TC -lpthread
Fork:
	gcc fork_server.c -o FS
	gcc thread_client.c -o TC -lpthread
ST:
	gcc simpleserver.c -o ss
	gcc thread_client.c -o tc -lpthread

